CREATE LOGIN [userMnhmh2] WITH PASSWORD = 'userMnhmh2' , DEFAULT_DATABASE=[MNHMH2], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
CREATE USER [userMnhmh2] FOR LOGIN [userMnhmh2];
USE [MNHMH2];
GO
ALTER ROLE db_owner ADD MEMBER userMnhmh2;