CREATE LOGIN [userMnhmh] WITH PASSWORD = '@userMnhmhPassword' , DEFAULT_DATABASE=[MNHMH], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
CREATE USER [userMnhmh] FOR LOGIN [userMnhmh];
GO
USE [MNHMH];
ALTER ROLE db_owner ADD MEMBER [userMnhmh];
GO